# 1-Array

In [7]:
import numpy as np
list=[1,2,3,4]
y=np.array([1,2,3,4])
print(list)
print(y)
print(type(y))
print(type(list))

[1, 2, 3, 4]
[1 2 3 4]
<class 'numpy.ndarray'>
<class 'list'>


In [8]:
y.ndim

1

In [12]:
ar2=np.array([[1,2,3,4],[2,3,4,5]])
print(ar2)
print(ar2.ndim)

[[1 2 3 4]
 [2 3 4 5]]
2


In [13]:
# 3 Dimension array
ar3=np.array([[[1,2,3],[1,2,3],[1,2,3,]]])
print(ar3)
print(ar3.ndim)

[[[1 2 3]
  [1 2 3]
  [1 2 3]]]
3


In [19]:
# multi_Dimension
arn=np.array([1,2,3,4],ndmin=10)
print(arn)
print(arn.ndim)

[[[[[[[[[[1 2 3 4]]]]]]]]]]
10


## 2-Zero

In [23]:
ar_zero=np.zeros(4)
ar2_zero=np.zeros((3,4))

print(ar_zero)
print()
print(ar2_zero)


[0. 0. 0. 0.]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


## 3-ones

In [29]:
ar_one=np.ones(4)
print(ar_one)
ar2_one=np.ones((3,4))
print()
print(ar2_one)

[1. 1. 1. 1.]

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


## 4-Empty

In [32]:
ar_empty=np.empty(4)
print(ar_empty)

[1. 1. 1. 1.]


## 5-Range

In [34]:
range=np.arange(4)
print(range)

[0 1 2 3]


In [38]:
range2=np.arange(1,10,2)
print(range2)

[1 3 5 7 9]


## 6-Diagonal

In [40]:
# eye use for diagonal
ar_dia=np.eye(4)
print(ar_dia)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [42]:
ar_dia2=np.eye(2,2)
print(ar_dia2)

[[1. 0.]
 [0. 1.]]


## 7-linspace



In [46]:
lin=np.linspace(1,10, num=5)
print(lin)

[ 1.    3.25  5.5   7.75 10.  ]
